### ISSUE TITLE
SEGV on unknown address 0x000000000000

### ISSUE THREAD

**Issue by dzonerzy** [ccxvii/mujs#105]
$ ./build/sanitize/mujs a.js 
ASAN:DEADLYSIGNAL
=================================================================
==14039==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x561be0fa9e67 bp 0x7ffdec50f2d0 sp 0x7ffdec50f2a0 T0)
==14039==The signal is caused by a READ memory access.
==14039==Hint: address points to the zero page.
    #0 0x561be0fa9e66 in compile /home/fuzzing/Desktop/mujs/regexp.c:644
    #1 0x561be0fab982 in js_regcompx /home/fuzzing/Desktop/mujs/regexp.c:884
    #2 0x561be0f89bca in js_newregexp /home/fuzzing/Desktop/mujs/jsregexp.c:19
    #3 0x561be0f9e2d7 in Sp_match /home/fuzzing/Desktop/mujs/jsstring.c:338
    #4 0x561be0f956f5 in jsR_callcfunction /home/fuzzing/Desktop/mujs/jsrun.c:1041
    #5 0x561be0f960b2 in js_call /home/fuzzing/Desktop/mujs/jsrun.c:1083
    #6 0x561be0f99ca2 in jsR_run /home/fuzzing/Desktop/mujs/jsrun.c:1511
    #7 0x561be0f95498 in jsR_callscript /home/fuzzing/Desktop/mujs/jsrun.c:1024
    #8 0x561be0f95f67 in js_call /home/fuzzing/Desktop/mujs/jsrun.c:1079
    #9 0x561be0f9bc26 in js_dofile /home/fuzzing/Desktop/mujs/jsstate.c:207
    #10 0x561be0fb031d in main /home/fuzzing/Desktop/mujs/main.c:347
    #11 0x7f61855fdb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #12 0x561be0f4ec19 in _start (/home/fuzzing/Desktop/mujs/build/sanitize/mujs+0x16c19)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/fuzzing/Desktop/mujs/regexp.c:644 in compile
==14039==ABORTING

```
"AAAAAAAAAAA".match("(?:!)(?:)")

```

This is caused by node in compile being NULL

**Comment by dzonerzy** [comment]
Closing fixed with e2b59201d5049a8ad509b280e729a871756abc99
